// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMC0QiKNUOCjIt1PCUhCU8z1FpqhiJL2o',
    appId: '1:448117077731:web:4bdf7cf0c3e56c0cf877d6',
    messagingSenderId: '448117077731',
    projectId: 'asret-dc490',
    authDomain: 'asret-dc490.firebaseapp.com',
    storageBucket: 'asret-dc490.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA59iXP7WvP_ZxlF1o6gmlLZRQsYxqLgjY',
    appId: '1:448117077731:android:4e2220d47c35f3a2f877d6',
    messagingSenderId: '448117077731',
    projectId: 'asret-dc490',
    storageBucket: 'asret-dc490.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7CG2I7Gum10jBbQ2xT0ogKSr-OrlP7_A',
    appId: '1:448117077731:ios:87203754610abdbbf877d6',
    messagingSenderId: '448117077731',
    projectId: 'asret-dc490',
    storageBucket: 'asret-dc490.appspot.com',
    iosBundleId: 'com.example.astret',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7CG2I7Gum10jBbQ2xT0ogKSr-OrlP7_A',
    appId: '1:448117077731:ios:d7c0c9c8fbd51977f877d6',
    messagingSenderId: '448117077731',
    projectId: 'asret-dc490',
    storageBucket: 'asret-dc490.appspot.com',
    iosBundleId: 'com.example.astret.RunnerTests',
  );
}
